/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/orgs/{orgId}/workflow-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List workflow templates for an org */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkflowTemplateResponse"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a workflow template */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateWorkflowTemplateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkflowTemplateResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/workflow-templates/{templateId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single workflow template */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgId: string;
                    templateId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkflowTemplateResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit a workflow template (name, requires_warmup, and/or steps)
         * @description Never affects an Enrollment already running against this template — Enrollment.steps is a separate, frozen snapshot taken at enrollment time.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgId: string;
                    templateId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateWorkflowTemplateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkflowTemplateResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/orgs/{orgId}/workflow-templates/{templateId}/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enroll every lead in a SavedList into this workflow template */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgId: string;
                    templateId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EnrollSavedListRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnrollSavedListResponse"];
                    };
                };
                /** @description Empty template, or the SavedList belongs to a different org */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Template or SavedList not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/email-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List email templates for an org */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmailTemplateResponse"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgId}/email-templates/{templateId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List an email template's versions
         * @description Pass status=APPROVED to get the set safe to pin a workflow email step to — a WorkflowStep pins to a specific EmailTemplateVersion id, never "latest".
         */
        get: {
            parameters: {
                query?: {
                    status?: "DRAFT" | "PENDING_APPROVAL" | "APPROVED" | "REJECTED" | "RESUBMITTED";
                };
                header?: never;
                path: {
                    orgId: string;
                    templateId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EmailTemplateVersionResponse"][];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        WorkflowStepInput: {
            /** @enum {string} */
            kind: "email" | "call_task" | "sms" | "wait";
            /** @description Required, email only — pins a specific approved EmailTemplateVersion, never "latest". */
            email_template_version_id?: string;
            /** @description Required, email only. */
            sending_domain?: string;
            /** @description Required, sms only. */
            sms_body?: string;
            /** @description Required, call_task only. */
            call_task_instructions?: string;
            /** @description Required, wait only. */
            wait_amount?: number;
            /**
             * @description Required, wait only.
             * @enum {string}
             */
            wait_unit?: "minutes" | "hours" | "days";
        };
        WorkflowStepResponse: components["schemas"]["WorkflowStepInput"] & {
            _id: string;
        };
        CreateWorkflowTemplateRequest: {
            name: string;
            /** @default false */
            requires_warmup: boolean;
            steps: components["schemas"]["WorkflowStepInput"][];
        };
        UpdateWorkflowTemplateRequest: {
            name?: string;
            requires_warmup?: boolean;
            steps?: components["schemas"]["WorkflowStepInput"][];
        };
        WorkflowTemplateResponse: {
            _id?: string;
            org_id?: string;
            name?: string;
            requires_warmup?: boolean;
            steps?: components["schemas"]["WorkflowStepResponse"][];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        EnrollSavedListRequest: {
            saved_list_id: string;
        };
        EnrollSavedListResponse: {
            enrolled_count?: number;
            skipped_count?: number;
            enrollment_ids?: string[];
        };
        ErrorResponse: {
            error?: string;
        };
        EmailTemplateResponse: {
            _id?: string;
            org_id?: string;
            name?: string;
            persona?: string;
            workflow_position?: string;
            current_version_id?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        EmailTemplateVersionResponse: {
            _id?: string;
            email_template_id?: string;
            version_number?: number;
            subject_line?: string;
            body_html?: string;
            /** @enum {string} */
            image_policy?: "always" | "never" | "auto";
            /** @enum {string} */
            generation_source?: "ai" | "human" | "ai_edited_by_human";
            /** @enum {string} */
            status?: "DRAFT" | "PENDING_APPROVAL" | "APPROVED" | "REJECTED" | "RESUBMITTED";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
